version: '0.0.1'
services:
 client:
  #   stdin_open: true
  restart: unless-stopped # always
  image: ${DOCKER_USER_NAME}/${APP_NAME}
  container_name: client
  build:
   context: ./client
   dockerfile: Dockerfile
  ports:
   - ${FRONT_PORT}:${FRONT_PORT}
  volumes:
   - src-files:/app/src
volumes:
 src-files:
# external: true
